import { ArrowDownward, ArrowUpward } from "@mui/icons-material";
import personImage from "./images/pexels-pixabay-220453.jpg";
import productImg from "./images/mwp22hn-a-apple-original-imag3qe9eqkfhmg8.jpeg";

export const featureInfoData = [
  {
    title: "Sales",
    money: "12,545",
    id: "f1",
    moneyRate: "-21.4%",
    icon: <ArrowDownward className="tJanmd ml-[5px] text-red-500" />,
  },
  {
    title: "Profit",
    money: "2,345",
    id: "f2",
    moneyRate: "-21.4%",
    icon: <ArrowDownward className="tJanmd ml-[5px] text-red-500" />,
  },
  {
    title: "Cost",
    money: "10,200",
    id: "f3",
    moneyRate: "+41.4%",
    icon: <ArrowUpward className="tJanmd ml-[5px] text-green-500" />,
  },
];

export const chartData = [
  {
    name: "Jan",
    sales: 4000,
    profit: 2400,
    cost: 2400,
  },
  {
    name: "Feb",
    sales: 3000,
    profit: 1398,
    cost: 2210,
  },
  {
    name: "Mar",
    sales: 2000,
    profit: 9800,
    cost: 2290,
  },
  {
    name: "Apr",
    sales: 2780,
    profit: 3908,
    cost: 2000,
  },
  {
    name: "May",
    sales: 1890,
    profit: 4800,
    cost: 2181,
  },
  {
    name: "Jun",
    sales: 2390,
    profit: 3800,
    cost: 2500,
  },
  {
    name: "July",
    sales: 3490,
    profit: 2600,
    cost: 2700,
  },
  {
    name: "Aug",
    sales: 3590,
    profit: 9300,
    cost: 2200,
  },
  {
    name: "Sep",
    sales: 3690,
    profit: 2300,
    cost: 1200,
  },
  {
    name: "Oct",
    sales: 2490,
    profit: 3500,
    cost: 8700,
  },
  {
    name: "Nov",
    sales: 3470,
    profit: 7300,
    cost: 5100,
  },
  {
    name: "Dec",
    sales: 3290,
    profit: 4350,
    cost: 2100,
  },
];
export const productChartData = [
  {
    name: "Jan",
    sales: 2000,
    profit: 2700,
    cost: 1200,
  },
  {
    name: "Feb",
    sales: 4000,
    profit: 2398,
    cost: 2510,
  },
  {
    name: "Mar",
    sales: 7000,
    profit: 9800,
    cost: 4290,
  },
];

export const widgetSmData = [
  {
    id: "p1",
    img: personImage,
    name: "Manish Navlani",
    job: "Web Developer",
  },
  {
    id: "p2",
    img: personImage,
    name: "Devidas Navlani",
    job: "Web Developer",
  },
  {
    id: "p3",
    img: personImage,
    name: "Nisha Navlani",
    job: "Web Developer",
  },
  {
    id: "p4",
    img: personImage,
    name: "Suman Navlani",
    job: "Web Developer",
  },
  {
    id: "p5",
    img: personImage,
    name: "Kishor Navlani",
    job: "Web Developer",
  },
];

export const userListData = [
  {
    id: 1,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 11,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 12,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 13,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 14,
    username: "Jon Snow",
    avatar: personImage,
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];
export const productListData = [
  {
    id: 1,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 11,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 12,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 13,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 14,
    productName: "Apple Airpods",
    productImg,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
];
